version: "3.8"

services:
  playwright:
    build: .
    working_dir: /app
    volumes:
      - .:/app:Z
      - ./playwright-report:/app/playwright-report:Z
    env_file: .env
    environment:
      - TZ=Europe/Minsk
    ipc: host
    stdin_open: true
    tty: true
    command: npm run ${TEST_SCRIPT:-test:all}
