name: Playwright Tests Sequential Reports

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  oauth:
    uses: ./.github/workflows/playwright-test.yml
    with:
      test-script: test:api:no_oauth
    secrets: inherit

  deploy-oauth:
    needs: [oauth]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download HTML report artifact
        uses: actions/download-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/

      - name: Debug downloaded report
        run: |
          pwd
          ls -la
          # ls -R
          # ls -R playwright-report

      - name: Deploy OAuth Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./playwright-report
