name: Playwright Tests
on: [push, pull_request]

jobs:
  oauth:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: make test-oauth
        env:
          BASE_URL_AUTH: ${{ secrets.BASE_URL_AUTH }}
          API_KEY: ${{ secrets.API_KEY }}
          CI: "true"
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report-oauth
          path: playwright-report/

  no_oauth:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: make test-no_oauth
        env:
          BASE_URL_NO_AUTH: ${{ secrets.BASE_URL_NO_AUTH }}
          API_KEY: ${{ secrets.API_KEY }}
          CI: "true"
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report-no_oauth
          path: playwright-report/

  ui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: make test-ui
        env:
          BASE_URL_UI: ${{ secrets.BASE_URL_UI }}
          API_KEY: ${{ secrets.API_KEY }}
          CI: "true"
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report-ui
          path: playwright-report/
